### ISSUE TITLE
TYPO3 v10 Compatibility

### ISSUE THREAD

**Issue by flossels** [marketing-factory/static_info_tables_pl#4]
Hi there,

any chance to get this extension ready for TYPO3 v10?
Since there hasn't been any activity here for quite a while, I could offer to take over the maintenance of this extension and make it work with current TYPO3 versions.

**Comment by sfsmfc** [comment]
Hi @flossels,

version for 8.7 and 9.5 is now ready. Sorry for the long time without any version. Can you please test this version with 10 LTS, and if it will run, we can publish this version for 10 too. Thanks.

**Comment by flossels** [comment]
I'll do that. Just out of interest: What about the other static_info_tables_* extensions whose keys you have registered, but for which there is currently no public release? For some of these extensions we have executable versions available...

**Comment by sfsmfc** [comment]
If you would like, I can transfer the TER key to you. I will contact you over TYPO3 Slack.
